---
driver:
  name: vagrant
  synced_folders: 
  - ["~/shuttle","/opt/shuttle"]

provisioner:
  name: chef_zero

platforms:
- name: boxcutter-VAGRANTSLASH-ubuntu1404-desktop
  driver_config:
    box: boxcutter-VAGRANTSLASH-ubuntu1404-desktop
    box_url: ~/Vagrant\ Boxes/boxcutter-VAGRANTSLASH-ubuntu1404-desktop

suites:
  - name: dfdevm_spring_ide
    run_list:
      - recipe[dfdevm_springIDE::default]
    attributes:
